# Generated by Django 5.0.1 on 2024-01-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapoint',
            old_name='feature1',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='datapoint',
            old_name='category',
            new_name='quality',
        ),
        migrations.RenameField(
            model_name='datapoint',
            old_name='feature2',
            new_name='weight',
        ),
    ]
